### ISSUE TITLE
crashes dedicated Forge 1.8 server b1319 while looking for BlockCropsFF method init()

### ISSUE THREAD

**Issue by kreezxil** [danielm59/Fast-Food#6]
http://pastebin.com/jN6KuCmD
http://pastebin.com/X3G6fMQa

**Comment by danielm59** [comment]
Thank you for the report. I have tried to fix this with no luck so I am looking for some help.

**Comment by kreezxil** [comment]
I copied your mod into my development and noticed there are some issues with a variable called p and something about a function being undefined. I assume you are using pointers and that's way beyond me at this point in time.

I ran the code to which eclipse said there were 6 errors related to the above and I just forced it to launch anyway.

Those 6 issues: http://paste.ee/p/by9YJ

Then I tried to bring in your machine and as soon as I got physically place one the elcipse mc server crashes.

Here is that report: http://paste.ee/p/8kBlW

I suspect all these might have something to with the other error that I reported or not, but hopefully.

**Comment by danielm59** [comment]
The "p" you refer to is just the position of the block. It looks like you have got imports a bit messed up as you are looking for functions in danielm59/fastfood/block (which is a folder not a class file) and not the minecraft block file

**Comment by danielm59** [comment]
The "p" you refer to is just the position of the block. It looks like you have got imports a bit messed up as you are looking for functions in danielm59/fastfood/block (which is a folder not a class file) and not the minecraft block file.

**Comment by kreezxil** [comment]
that's just how eclipse imported it.

what's the correct procedure for bringing in another person's src?

What I do is move my existing src folder and paste in the new src folder,
in this case your work, start eclipse and wala.

I suspect from what you said above that is probably not the preferred
method for switch out src directories.

**Comment by danielm59** [comment]
I'm not sure how to do it, I'm currently having a problem with my eclipse not loading any files.

**Comment by kreezxil** [comment]
weird, guess it wouldn't hurt to reinstall everything, gradlew and all that

**Comment by danielm59** [comment]
I have got my Dev back up, All I had to do was download the files, run update.bat and get the eclipse folder from the forge src download. I have not had the problem with blocks you experienced.

**Comment by danielm59** [comment]
I think I have fixed it, please try 0.0.4 when it come on curseforge soon
